#!/usr/bin/env python

import sys

from rqt_laser_sweep.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'rqt_laser_sweep'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
